# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set the default environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres

# Expose the default PostgreSQL port (5432)
EXPOSE 5432

# Start PostgreSQL when the container launches
CMD ["postgres"]
