version: '3.9'
name: swiftsell
services:
    web:
        env_file: '../.env.local'
        depends_on: ['firebase', 'api']
        container_name: web
        build:
            context: '../../../'
            dockerfile: apps/web/docker/Dockerfile.development
        restart: always
        ports:
            - '4200:4200'
        command: 'npx nx start web'
        volumes:
            - '../../web:/app/apps/web'
            - '../../api:/app/apps/api'
            - '../../db:/app/apps/db'
            - '../../firebase:/app/apps/firebase'
            - '../../../libs:/app/libs'
        networks:
            - frontend
            - backend
    api:
        env_file: '../../api/.env'
        depends_on: ['db']
        container_name: api
        command: 'npx nx start api'
        restart: always
        build:
            context: '../../../'
            dockerfile: apps/api/docker/Dockerfile.development
        ports:
            - '5000:5000'
        volumes:
            - '../../api:/app/apps/api'
            - '../../db:/app/apps/db'
            - '../../../libs:/app/libs'
        networks:
            - backend
    db:
        depends_on: ['shadow']
        container_name: postgres
        build:
            context: '../../../'
            dockerfile: apps/db/Dockerfile
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - '../../graphql/init.sql:/docker-entrypoint-initdb.d/init.sql'
        networks:
            - backend
    shadow:
        container_name: shadow
        build:
            context: '../../../'
            dockerfile: apps/db/Dockerfile
        restart: always
        ports:
            - '6543:5432'
        volumes:
            - '../../graphql/init.sql:/docker-entrypoint-initdb.d/init.sql'
        networks:
            - backend
    graphql:
        env_file: '../../graphql/.env.skeleton'
        container_name: hasura
        build:
            context: '../../../'
            dockerfile: apps/graphql/Dockerfile
        ports:
            - '9090:8080'
        depends_on: ['db']
        restart: always
        networks:
            - backend
    firebase:
        container_name: firebase
        env_file: '../../firebase/.env.skeleton'
        restart: always
        build:
            context: '../../../'
            dockerfile: apps/firebase/Dockerfile
        ports:
            - '4000:4000'
            - '5001:5001'
            - '8080:8080'
            - '8085:8085'
            - '9000:9000'
            - '9099:9099'
            - '9199:9199'
        networks:
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
