query getProducts($offset: Int!, $limit: Int!) {
    Product(offset: $offset, limit: $limit) {
        id
        name
        description
        price
        color
        size
        Images {
            id
            url
        }
    }
}
