query getProduct($id: Int!) {
    Product(where: { id: { _eq: $id } }) {
        id
        name
        description
        color
        size
        price
        Images {
            id
            url
        }
    }
}
